### PR TITLE
feat: setup e2e test

### PR DESCRIPTION
**Pull request by pyk**
## Description

[Register.app](http://register.app/) is the user-interface for the Reserve Protocol. It was built to allow users to deploy, view, use, and govern RTokens, and is currently doing its job well. There are currently no tests in the Register codebase. 

The goal of this badge is to setup an E2E testing framework that can be run locally and in github actions CI. [GuardianUI](https://www.guardianui.com/) should be used as the testing framework. 

## Deliverables

- [x] Setup an E2E testing framework in the Register repo, complete with a yarn command to run the tests locally. 
- [x] Setup a github action that runs the E2E tests in CI. 
- [x] Write an E2E test that forks from a recent mainnet block (hardcode this block in the repo) and issues 10,000 eUSD RTokens. The test can mock user balances of USDC, USDT, cUSDC, cUSDT, but it should wrap USDC & USDT into saUSDC & saUSDT via the UI, approve all 4 tokens via the UI, and issue eUSD via the UI. 
- [x] Write an E2E test that does something similar for ETH+ (can mock balances of both rETH and wstETH collateral tokens). 
- [x] Write an E2E test that does something similar for hyUSD (can mock balances of all 4 collateral tokens). 
- [x] Updated [README.md](http://readme.md/) with instructions on how to run the E2E tests locally.

### CODE REVIEW

**Review by lcamargof — COMMENTED** [review]
It looks great, 

The only problem is, the collateral list of an RToken (saUSDC, cUSDc, etc...) can change, this would break the tests as current collateral list per token is hardcoded into the test.

**Comment by pyk** [comment]
@lcamargof thank you so much for the review ser,

You're right, I forgot that the collateral list of an RToken can change, and that would break the tests if the current collateral list is hardcoded into the test. 

There is a way to address this. A simple solution would be to use [Facade Contract](https://github.com/lc-labs/register/blob/799edb824e7a326e960afa6b82bfec23b336da65/src/utils/addresses.ts#L19-L21) to fetch the current collateral list for each RToken.

Is it okay to fetch list of collaterals via Facade contract inside the test?

**Comment by lcamargof** [comment]
Yes, pulling the list of collaterals from the facade works 👍🏻

**Comment by pyk** [comment]
@lcamargof btw when I fetch list of collaterals then mock the balance via `gui.setBalance`, the test is always failed due to the balance is not set correctly. 

I have reported the issue to GuardianTest repo https://github.com/GuardianUI/GuardianTest/issues/32

Do we wait the issue is fixed or use the hardcoded collaterals for now?

**Comment by pyk** [comment]
Fixed by #141

**Pull request closed without merging**
